#define MICROPY_HW_BOARD_NAME       "ESP32-S3-FREENOVE-CAM"
#define MICROPY_HW_MCU_NAME         "ESP32S3"

#define MICROPY_HW_ENABLE_SDCARD    (0)
#define MICROPY_HW_ENABLE_SDCARD_MOUNT (0)

#define MICROPY_PY_MACHINE_SOFTI2C  (1)
#define MICROPY_PY_MACHINE_SOFTSPI  (1)
#define MICROPY_PY_MACHINE_I2S      (1)
